### ISSUE TITLE
Alpha diversity indices (Simpson indices) ?

### ISSUE THREAD

**Issue by marwa38** [gavinmdouglas/FuncDiv#3]
Giving FuncDiv a try thanks for the new package
I have a quick query if you could help please

Regarding 

- gini simpson index
- Simpson evenness

Do you know which one is the same as `Simpson `in `estimate_richness()` R documentation link [here](https://www.rdocumentation.org/packages/phyloseq/versions/1.16.2/topics/estimate_richness)
Or both (gini simpson index and Simpson evenness) are different than the one in `estimate_richness()`?
Table of simpson output I got from `estimate_richness()` if you would like to have a look:
![image](https://user-images.githubusercontent.com/68851733/218430455-e2b5a3c5-625c-409a-ac3b-5ef3664a818d.png)

As an update according to `estimate_richnness()`, Gini-Simpson is equal to 1- Simpson
https://github.com/joey711/phyloseq/issues/940, does this imply that Simpson evenness is the same as Simpson in `estimate_richnness()`?

Update2: I checked this [link ](http://scikit-bio.org/docs/latest/generated/skbio.diversity.alpha.html#module-skbio.diversity.alpha) you shared re skbio.diversity in python 
and found the following

1. [gini_index](http://scikit-bio.org/docs/latest/generated/skbio.diversity.alpha.gini_index.html#skbio.diversity.alpha.gini_index)(data[, method])
2. [simpson_e](http://scikit-bio.org/docs/latest/generated/skbio.diversity.alpha.simpson_e.html#skbio.diversity.alpha.simpson_e)(counts)
3. [simpson](http://scikit-bio.org/docs/latest/generated/skbio.diversity.alpha.simpson.html#skbio.diversity.alpha.simpson)(counts)
and couldn't find inverse Simpson?

I am confused, apologies if I missed something.

Thanks 
M

**Comment by gavinmdouglas** [comment]
Hi @marwa38,

The Gini-Simpson index is defined as shown here: http://scikit-bio.org/docs/latest/generated/skbio.diversity.alpha.simpson.html#skbio.diversity.alpha.simpson

And Simpson's evenness as defined here: http://scikit-bio.org/docs/latest/generated/skbio.diversity.alpha.simpson_e.html#skbio.diversity.alpha.simpson_e

I think you're right that Gini-Simpson should be the complement to what is computed by that function, although I would have to test it to be sure. I went with Gini-Simpson index as this was the form that was used predominately in prior contributional diversity analyses.


Cheers,

Gavin

**Comment by marwa38** [comment]
Thanks @gavinmdouglas 
I updated my query 
I am running on a desktop at the moment so might not have the privilege to try different options as it seems it is long time to run. 



> I think you're right that Gini-Simpson should be the complement to what is computed by that function, although I would have to test it to be sure. I went with Gini-Simpson index as this was the form that was used predominately in prior contributional diversity analyses.

the alpha diversity function have already 3 Simpson indices 

1. gini_simpson_index
2. simpsons_evenness
3. inverse_simpson_index

![image](https://user-images.githubusercontent.com/68851733/218479887-62ae90d3-e2c4-4ed5-ac78-a6fc0b90eeb9.png)
 
 Just for record will keep it here might be enriching to the discussion 
![image](https://user-images.githubusercontent.com/68851733/218482471-620a6e1a-00d5-45f4-b596-ac22e2d80519.png)

**Comment by gavinmdouglas** [comment]
Hi @marwa38,

Sorry I forgot about this thread!

I looked into the `estimate_richness` function in phyloseq, and saw that it calls the [`vegan` function `diversity`](https://rdrr.io/cran/vegan/man/diversity.html).

From the doc page for the `vegan` function:

`Both variants of Simpson's index are based on D = sum p_i^2. Choice simpson returns 1-D and invsimpson returns 1/D.`

In `FuncDiv`, the `inverse_simpson_index` is the same as `invsimpson`, and `gina_simpson_index` is the same as `simpson`.

`simpsons_evenness` returns the (Inverse Simpson Index) / (Observed Richness) (as [defined here](http://scikit-bio.org/docs/latest/generated/skbio.diversity.alpha.simpson_e.html#skbio.diversity.alpha.simpson_e)).


Hopefully that clears up the differences!

Gavin

**Comment by marwa38** [comment]
@gavinmdouglas  thanks for this. 
number of observed OTUs as a definition for the richness in simpsons_evenness that you kindly shared is the same definition of 
of `richness` in `FuncDiv`? as I couldn't find `richness` as an index separately defined in http://scikit-bio.org/

**Comment by gavinmdouglas** [comment]
Hi there,

Yes 'observed OTUs' refers to the number of different OTUs observed in the sequencing data for a sample.

Richness just means the number of different types of elements in a sample (in this case the taxa, which could be OTUs). People often like to emphasize that this is 'observed' richness in the sequencing data, rather than corresponding to the actual count of different taxa in reality (i.e., if you quantified systematically by eye in nature, which makes more sense for non-microbes).


Cheers,

Gavin
