### ISSUE TITLE
CRAN/Bioconductor release?

### ISSUE THREAD

**Issue by nick-youngblut** [gavinmdouglas/FuncDiv#5]
Great package! Are there any plans on publishing the package on CRAN or Bioconductor? Package availability via CRAN/Bioconductor helps with package installation & management, especially for conda-based installations of R packages.

**Comment by gavinmdouglas** [comment]
Thanks - yes, I am planning on releasing it on CRAN soon!

**Comment by gavinmdouglas** [comment]
FuncDiv is now released on CRAN! https://cran.r-project.org/package=FuncDiv
