### ISSUE TITLE
Downstream visualisation examples?

### ISSUE THREAD

**Issue by marwa38** [gavinmdouglas/FuncDiv#9]
Hi Gavin

I know they you don't want to her a template code for how to visualise results from funcDiv but I think that having some examples of downstream analysis would help funcDiv to spread how useful it could be for end-users as mostly biologists are not working with bioinformatician. 

Thanks 
Marwa

**Comment by gavinmdouglas** [comment]
Hi @marwa38,

Sorry, just seeing your message now.

At the moment I do not have any other visualization examples other than the heatmap. This is an relatively new data type that can be useful in principle, but there is no set workflow that users can use without doing exploratory data analysis themselves.


Cheers,

Gavin
